// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  actor: dynamic(() => import("./Talent")),
  actorordering: dynamic(() => import("./Actorordering")),
  article: dynamic(() => import("./Article")),
  contact: dynamic(() => import("./Contact")),
  diapo: dynamic(() => import("./Carousel")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  homepage: dynamic(() => import("./Homepage")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  package: dynamic(() => import("./Package")),
  package2: dynamic(() => import("./Package2")),
  representation: dynamic(() => import("./Representation")),
  talents_gallery: dynamic(() => import("./TalentsGallery")),
  video_home_page: dynamic(() => import("./VideoHomePage")),
};
