// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  rich_text: dynamic(() => import("./RichText")),
  video_home_page: dynamic(() => import("./VideoHomePage")),
};
